# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 546ebfa5073a001f4f820bb35b008d00fd241f75cf6b563b63ac4dfbd12ea29985b6faf93431f66868abbf7c1dc325526162cf84feee9428212676b460b783b8

test:
  secret_key_base: 17c3ca7dc99f4a51633398d15dded40b9b1b52dc457faaee42295360c3efa75d88762207c682e871de6e06f6be5c39c493dabb0c697692fa94bf844eab7cfdbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
